### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Mikkel1803** [benov84/homebridge-chromecast-speaker#3]
not sure what the problem is as I'm new to homebridge.

I'm getting this message when installing:

1 error generated.
gmake: *** [dns_sd_bindings.target.mk:180: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
gmake: Leaving directory '/usr/local/lib/node_modules/homebridge-chromecast-television/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System FreeBSD 12.2-RELEASE-p3
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-chromecast-television/node_modules/mdns
gyp ERR! node -v v16.10.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-29T10_18_48_493Z-debug.log

can you help me with what I'm doing wrong

**Comment by TheGithubJoshua** [comment]
I'm having the same issue.

**Comment by benov84** [comment]
This is related with installing mdns library, a prerequisite to this repository.

https://github.com/agnat/node_mdns

Try to install the library itself using the instructions and file an issue there, please.
