### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by andrewmin** [benov84/homebridge-chromecast-speaker#4]
I tried to install homebridge-chromecast-speaker using Homebridge-UI.

'npm ERR! compilation terminated.
npm ERR! make: *** [dns_sd_bindings.target.mk:183: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.4.0-99-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/lib/node_modules/homebridge-chromecast-speaker/node_modules/mdns
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-02-12T23_23_19_651Z-debug-0.log

Command failed. Please review log for details.'

**Comment by TheGithubJoshua** [comment]
same issue.

**Comment by benov84** [comment]
This is related with installing mdns library, a prerequisite to this repository.

https://github.com/agnat/node_mdns

Try to install the library itself using the instructions and file an issue there, please.
