### ISSUE TITLE
Log error: homebridge and hap-nodejs

### ISSUE THREAD

**Issue by dustin555** [benov84/homebridge-chromecast-speaker#5]
After installing v1.0.1, I receive this error in my log:
>_The plugin "homebridge-chromecast-speaker" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!_

I know it's been a minute since any updates have been issued for this plug-in, so does anyone have any ideas how to overcome this error?

**Comment by benov84** [comment]
I have fixed this, I hope. Please update to version 1.0.2 and see if it works. I'm personally not using this plugin anymore, so cannot test it that quick.

**Comment by benov84** [comment]
Another update - 1.0.3

**Comment by dustin555** [comment]
Error is gone now. Thanks for handling it so quickly!

**Comment by dustin555** [comment]
@benov84, are you using anything similar now? 

I'm hoping to use this plugin with [homebridge-device-alive](https://github.com/marcveens/homebridge-device-alive) to trigger another device if the Chromecast is actively streaming. 

Thanks again for your work!

**Comment by benov84** [comment]
@benov84, are you using anything similar now? - I'm not using my Google Home speaker with HomeKit right now. I have made this plug in to add it HomeKit, but there wasn't support with native Home app at the moment, and I have removed it from HomeKit.
I hope everything is fine now with your device! Thanks
