### ISSUE TITLE
Accessory Not Supported

### ISSUE THREAD

**Issue by shanekelly55** [benov84/homebridge-chromecast-speaker#6]
I installed the plugin and it found all my Chromecast Audio dingles as well as my Speaker Groups and Google Speakers.

But Apple home tells me: "This accessory is not currently supported by the Home App."

Any ideas?

**Comment by ethan-dh** [comment]
![image](https://github.com/benov84/homebridge-chromecast-speaker/assets/74271259/e2e62cb3-c20c-4d80-8412-8ffac3bdc492)

its written in the readme its normal
